var compo = compo || {};
compo = {
	main_form :()=>{
		return '<div class="jumbotron text-center">'
		+'  <h1>Bit Company</h1> '
		+'  <p>We specialize in blablabla</p> '
		+'</div>'
	},
	cust_login_form : ()=>{
		return '<h2>Login Form</h2>'
		+'<form>'
		+' <div class="imgcontainer">'
		+'    <img src="/img_avatar2.png" alt="Avatar" class="avatar">'
		+'  </div>'
		+'  <div class="container">'
		+'    <label for="uname"><b>Username</b></label>'
		+'    <input type="text" placeholder="Enter Username" name="uname" required>'
		+'    <label for="psw"><b>Password</b></label>'
		+'    <input type="password" placeholder="Enter Password" name="psw" required>'
		+'    <button type="submit">Login</button>'
		+'    <label>'
		+'      <input type="checkbox" checked="checked" name="remember"> Remember me'
		+'    </label>'
		+'  </div>'
		+'  <div class="container" style="background-color:#f1f1f1">'
		+'    <button type="button" class="cancelbtn">Cancel</button>'
		+'    <span class="psw">Forgot <a href="#">password?</a></span>'
		+'  </div>'
		+'</form>'
	},
	cust_join_form : ()=>{
		return '<form style="border:1px solid #ccc">'
		+'  <div class="container">'
		+'    <h1>Sign Up</h1>'
		+'    <p>Please fill in this form to create an account.</p>'
		+'    <hr>'
		+'<div name="rm">'
		+'    <label for="email"><b>Email</b></label>'
		+'    <input type="text" placeholder="Enter Email" name="email" required>'
		+'    <label for="psw"><b>Password</b></label>'
		+'    <input type="password" placeholder="Enter Password" name="psw" required>'
		+'    <label for="psw-repeat"><b>Repeat Password</b></label>'
		+'    <input type="password" placeholder="Repeat Password" name="psw-repeat" required>'
		+'</div>'
		+'    <label>'
		+'      <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me'
		+'    </label>'
		+'    <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>'
		+'    <div class="clearfix">'
		+'      <button type="button" class="cancelbtn">Cancel</button>'
		+'      <button type="submit" class="signupbtn">Sign Up</button>'
		+'    </div>'
		+'  </div>'
		+'</form>'
	},
	emp_access_form : ()=>{
		return '<h2>Login Form</h2>'
		+'<form action="/action_page.php">'
		+' <div class="imgcontainer">'
		+'    <img src="/img_avatar2.png" alt="Avatar" class="avatar">'
		+'  </div>'
		+'  <div class="container">'
		+'    <label for="employeeID"><b>Employee ID</b></label>'
		+'    <input type="text" placeholder="Enter employeeID" name="employeeID" required>'
		+'    <label for="name"><b>Name</b></label>'
		+'    <input type="text" placeholder="Enter Name" name="name" required>'
		+'    <button type="submit">Login</button>'
		+'    <label>'
		+'      <input type="checkbox" checked="checked" name="remember"> Remember me'
		+'    </label>'
		+'  </div>'
		+'  <div class="container" style="background-color:#f1f1f1">'
		+'    <button type="button" class="cancelbtn">Cancel</button>'
		+'    <span class="psw">Forgot <a href="#">password?</a></span>'
		+'  </div>'
		+'</form>'
	},
	emp_register_form : ()=>{
		return '<form style="border:1px solid #ccc">'
		+'  <div class="container">'
		+'    <h1>Sign Up</h1>'
		+'    <p>Please fill in this form to create an account.</p>'
		+'    <hr>'
		+'    <label for="email"><b>Email</b></label>'
		+'    <input type="text" placeholder="Enter Email" name="email" required>'
		+'    <label for="psw"><b>Password</b></label>'
		+'    <input type="password" placeholder="Enter Password" name="psw" required>'
		+'    <label for="psw-repeat"><b>Repeat Password</b></label>'
		+'    <input type="password" placeholder="Repeat Password" name="psw-repeat" required>'
		+'    <label>'
		+'      <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me'
		+'    </label>'
		+'    <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>'
		+'    <div class="clearfix">'
		+'      <button type="button" class="cancelbtn">Cancel</button>'
		+'      <button type="submit" class="signupbtn">Sign Up</button>'
		+'    </div>'
		+'  </div>'
		+'</form>'
	},
	cust_profil_form :(d)=>{ 
		return '<div class="w3-content w3-margin-top" style="max-width:1400px;">'
		+'  <!-- The Grid -->'
		+'  <div class="w3-row-padding">'
		+'    <!-- Left Column -->'
		+'    <div class="w3-third">'
		+'      <div class="w3-white w3-text-grey w3-card-4">'
		+'        <div class="w3-display-container">'
		+'          <img src="/w3images/avatar_hat.jpg" style="width:100%" alt="Avatar">'
		+'          <div class="w3-display-bottomleft w3-container w3-text-black">'
		+'            <h2>'+d.customerID+'</h2>'
		+'          </div>'
		+'        </div>'
		+'        <div class="w3-container">'
		+'          <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i>이름: '+d.customerName+'</p>'
		+'          <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i>휴대폰번호 : '+d.phone+'</p>'
		+'          <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i>주소 : '+d.city+'</p>'
		+'          <p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-teal"></i>상세주소 : '+d.address+'</p>'
		+'          <hr>'
		+'          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Skills</b></p>'
		+'          <p>Java</p>'
		+'          <div class="w3-light-grey w3-round-xlarge w3-small">'
		+'            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:90%">90%</div>'
		+'          </div>'
		+'          <p>JavaScript</p>'
		+'          <div class="w3-light-grey w3-round-xlarge w3-small">'
		+'            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:85%">'
		+'              <div class="w3-center w3-text-white">85%</div>'
		+'            </div>'
		+'          </div>'
		+'          <p>Ajax</p>'
		+'          <div class="w3-light-grey w3-round-xlarge w3-small">'
		+'            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:85%">85%</div>'
		+'          </div>'
		+'          <p>SQL</p>'
		+'          <div class="w3-light-grey w3-round-xlarge w3-small">'
		+'            <div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:80%">80%</div>'
		+'          </div>'
		+'          <br>'
		+'          <p class="w3-large w3-text-theme"><b><i class="fa fa-globe fa-fw w3-margin-right w3-text-teal"></i>Languages</b></p>'
		+'          <p>English</p>'
		+'          <div class="w3-light-grey w3-round-xlarge">'
		+'            <div class="w3-round-xlarge w3-teal" style="height:24px;width:100%"></div>'
		+'          </div>'
		+'          <p>Spanish</p>'
		+'          <div class="w3-light-grey w3-round-xlarge">'
		+'            <div class="w3-round-xlarge w3-teal" style="height:24px;width:55%"></div>'
		+'          </div>'
		+'          <p>German</p>'
		+'          <div class="w3-light-grey w3-round-xlarge">'
		+'            <div class="w3-round-xlarge w3-teal" style="height:24px;width:25%"></div>'
		+'          </div>'
		+'          <br>'
		+'        </div>'
		+'      </div><br>'
		+'    <!-- End Left Column -->'
		+'    </div>'
		+'    <!-- Right Column -->'
		+'    <div class="w3-twothird">'
		+'      <div class="w3-container w3-card w3-white w3-margin-bottom">'
		+'        <h2 class="w3-text-grey w3-padding-16">정보수정</h2>'
		+'        <div class="w3-container">'
		+'    <label for="password"><b>비밀번호</b></label>'
		+'    <input type="password" placeholder="modify password" name="password" value="'+d.password+'">'
		+'          <hr>'
		+'    <label for="city"><b>주소</b></label>'
		+'    <input type="text" placeholder="modify city" name="city" value="'+d.city+'" >'
		+'          <hr>'
		+'    <label for="address"><b>상세주소</b></label>'
		+'    <input type="text" placeholder="modify address" name="address" value="'+d.address+'" >'
		+'          <hr>'
		+'    <label for="postalCode"><b>우편번호</b></label>'
		+'    <input type="text" placeholder="modify postalCode" name="postalCode" value="'+d.postalCode+'" >'
		+'          <hr>'
		+'    <button type="submit">Update</button>'
		+'        </div>'
		+'      <div class="w3-container w3-card w3-white">'
		+'        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>Education</h2>'
		+'        <div class="w3-container">'
		+'          <h5 class="w3-opacity"><b>W3Schools.com</b></h5>'
		+'          <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i>Forever</h6>'
		+'          <p>Web Development! All I need to know in one place</p>'
		+'          <hr>'
		+'        </div>'
		+'        <div class="w3-container">'
		+'          <h5 class="w3-opacity"><b>London Business School</b></h5>'
		+'          <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i>2013 - 2015</h6>'
		+'          <p>Master Degree</p>'
		+'          <hr>'
		+'        </div>'
		+'        <div class="w3-container">'
		+'          <h5 class="w3-opacity"><b>School of Coding</b></h5>'
		+'          <h6 class="w3-text-teal"><i class="fa fa-calendar fa-fw w3-margin-right"></i>2010 - 2013</h6>'
		+'          <p>Bachelor Degree</p><br>'
		+'        </div>'
		+'      </div>'
		+'    <!-- End Right Column -->'
		+'    </div>  '
		+'  <!-- End Grid -->'
		+'  </div> '
		+'  <!-- End Page Container -->'
		+'</div>'
	}
}


